Repository Flow-Launcher/Flow.Launcher.PluginsManifest, pull requests merged in 2021-12, with the labels that each got.

#99 Add Tenor Flow
  plugins.json
Labels: Plugin Submission

#98 Update python plugins to working download url
  plugins.json
Labels: bug

#103 fix plugin tester ci
  .github/workflows/python-passed.yml
Labels: bug

#114 Add Emoji+ to manifest
  plugins.json
Labels: Plugin Submission

#115 Break loop on first detected Python plugin at bottom of dict
  ci/src/test-python.py
Labels: Continuous Integration/Workflow
