Repository Flow-Launcher/Flow.Launcher.PluginsManifest, pull requests merged in 2022-10, with the labels that each got.

#181 Add DateAdded & LatestReleaseDate fields
  .gitignore
  ci/src/_utils.py
  ci/src/update-tested.py
  ci/src/updater.py
Labels: Continuous Integration/Workflow

#178 Translation plugin nodejs
  .gitignore
  plugins.json
Labels: Plugin Submission

#183 Update GoogleSearch icon image
  plugins.json
Labels: bug

#186 update: 修改了图标的地址和插件名
  plugins.json
Labels: enhancement

#185 Add Cider Plugin
  plugins.json
Labels: Plugin Submission

#184 Remove Spell Checker Plugin
  plugins.json
Labels: bug

#187 Catch and skip plugins with errors
  ci/src/updater.py
Labels: Continuous Integration/Workflow
