Repository Flow-Launcher/Flow.Launcher.PluginsManifest, pull requests merged in 2023-02, with the labels that each got.

#206 Add JetBrainsIDEProjects plugin
  plugins.json
Labels: Plugin Submission

#208 Add JavaScript & TypeScript languages
  ci/src/_utils.py
Labels: Continuous Integration/Workflow

#205 Add HowLongToBeat Plugin
  plugins.json
Labels: Plugin Submission

#207 Added Tailwindcss Docs Plugin
  plugins.json
Labels: Plugin Submission

#209 Update Hello World Node.js plugin language reference
  plugins.json
Labels: bug

#210 Update language
  plugins.json
Labels: bug

#211 Update plugin language
  plugins.json
Labels: bug
